# Generated by Django 3.2.3 on 2022-05-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_pro', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_pro', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
